// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/eos/ent/chapter"
	"github.com/zibbp/eos/ent/predicate"
	"github.com/zibbp/eos/ent/video"
)

// ChapterUpdate is the builder for updating Chapter entities.
type ChapterUpdate struct {
	config
	hooks    []Hook
	mutation *ChapterMutation
}

// Where appends a list predicates to the ChapterUpdate builder.
func (cu *ChapterUpdate) Where(ps ...predicate.Chapter) *ChapterUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetTitle sets the "title" field.
func (cu *ChapterUpdate) SetTitle(s string) *ChapterUpdate {
	cu.mutation.SetTitle(s)
	return cu
}

// SetStartTime sets the "start_time" field.
func (cu *ChapterUpdate) SetStartTime(f float64) *ChapterUpdate {
	cu.mutation.ResetStartTime()
	cu.mutation.SetStartTime(f)
	return cu
}

// AddStartTime adds f to the "start_time" field.
func (cu *ChapterUpdate) AddStartTime(f float64) *ChapterUpdate {
	cu.mutation.AddStartTime(f)
	return cu
}

// SetEndTime sets the "end_time" field.
func (cu *ChapterUpdate) SetEndTime(f float64) *ChapterUpdate {
	cu.mutation.ResetEndTime()
	cu.mutation.SetEndTime(f)
	return cu
}

// AddEndTime adds f to the "end_time" field.
func (cu *ChapterUpdate) AddEndTime(f float64) *ChapterUpdate {
	cu.mutation.AddEndTime(f)
	return cu
}

// SetVideoID sets the "video" edge to the Video entity by ID.
func (cu *ChapterUpdate) SetVideoID(id string) *ChapterUpdate {
	cu.mutation.SetVideoID(id)
	return cu
}

// SetVideo sets the "video" edge to the Video entity.
func (cu *ChapterUpdate) SetVideo(v *Video) *ChapterUpdate {
	return cu.SetVideoID(v.ID)
}

// Mutation returns the ChapterMutation object of the builder.
func (cu *ChapterUpdate) Mutation() *ChapterMutation {
	return cu.mutation
}

// ClearVideo clears the "video" edge to the Video entity.
func (cu *ChapterUpdate) ClearVideo() *ChapterUpdate {
	cu.mutation.ClearVideo()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChapterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ChapterMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChapterUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChapterUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChapterUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChapterUpdate) check() error {
	if _, ok := cu.mutation.VideoID(); cu.mutation.VideoCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Chapter.video"`)
	}
	return nil
}

func (cu *ChapterUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chapter.Table,
			Columns: chapter.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: chapter.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Title(); ok {
		_spec.SetField(chapter.FieldTitle, field.TypeString, value)
	}
	if value, ok := cu.mutation.StartTime(); ok {
		_spec.SetField(chapter.FieldStartTime, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedStartTime(); ok {
		_spec.AddField(chapter.FieldStartTime, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.EndTime(); ok {
		_spec.SetField(chapter.FieldEndTime, field.TypeFloat64, value)
	}
	if value, ok := cu.mutation.AddedEndTime(); ok {
		_spec.AddField(chapter.FieldEndTime, field.TypeFloat64, value)
	}
	if cu.mutation.VideoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.VideoTable,
			Columns: []string{chapter.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: video.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.VideoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.VideoTable,
			Columns: []string{chapter.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: video.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChapterUpdateOne is the builder for updating a single Chapter entity.
type ChapterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChapterMutation
}

// SetTitle sets the "title" field.
func (cuo *ChapterUpdateOne) SetTitle(s string) *ChapterUpdateOne {
	cuo.mutation.SetTitle(s)
	return cuo
}

// SetStartTime sets the "start_time" field.
func (cuo *ChapterUpdateOne) SetStartTime(f float64) *ChapterUpdateOne {
	cuo.mutation.ResetStartTime()
	cuo.mutation.SetStartTime(f)
	return cuo
}

// AddStartTime adds f to the "start_time" field.
func (cuo *ChapterUpdateOne) AddStartTime(f float64) *ChapterUpdateOne {
	cuo.mutation.AddStartTime(f)
	return cuo
}

// SetEndTime sets the "end_time" field.
func (cuo *ChapterUpdateOne) SetEndTime(f float64) *ChapterUpdateOne {
	cuo.mutation.ResetEndTime()
	cuo.mutation.SetEndTime(f)
	return cuo
}

// AddEndTime adds f to the "end_time" field.
func (cuo *ChapterUpdateOne) AddEndTime(f float64) *ChapterUpdateOne {
	cuo.mutation.AddEndTime(f)
	return cuo
}

// SetVideoID sets the "video" edge to the Video entity by ID.
func (cuo *ChapterUpdateOne) SetVideoID(id string) *ChapterUpdateOne {
	cuo.mutation.SetVideoID(id)
	return cuo
}

// SetVideo sets the "video" edge to the Video entity.
func (cuo *ChapterUpdateOne) SetVideo(v *Video) *ChapterUpdateOne {
	return cuo.SetVideoID(v.ID)
}

// Mutation returns the ChapterMutation object of the builder.
func (cuo *ChapterUpdateOne) Mutation() *ChapterMutation {
	return cuo.mutation
}

// ClearVideo clears the "video" edge to the Video entity.
func (cuo *ChapterUpdateOne) ClearVideo() *ChapterUpdateOne {
	cuo.mutation.ClearVideo()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChapterUpdateOne) Select(field string, fields ...string) *ChapterUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chapter entity.
func (cuo *ChapterUpdateOne) Save(ctx context.Context) (*Chapter, error) {
	return withHooks[*Chapter, ChapterMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChapterUpdateOne) SaveX(ctx context.Context) *Chapter {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChapterUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChapterUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChapterUpdateOne) check() error {
	if _, ok := cuo.mutation.VideoID(); cuo.mutation.VideoCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Chapter.video"`)
	}
	return nil
}

func (cuo *ChapterUpdateOne) sqlSave(ctx context.Context) (_node *Chapter, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   chapter.Table,
			Columns: chapter.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: chapter.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chapter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chapter.FieldID)
		for _, f := range fields {
			if !chapter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chapter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Title(); ok {
		_spec.SetField(chapter.FieldTitle, field.TypeString, value)
	}
	if value, ok := cuo.mutation.StartTime(); ok {
		_spec.SetField(chapter.FieldStartTime, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedStartTime(); ok {
		_spec.AddField(chapter.FieldStartTime, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.EndTime(); ok {
		_spec.SetField(chapter.FieldEndTime, field.TypeFloat64, value)
	}
	if value, ok := cuo.mutation.AddedEndTime(); ok {
		_spec.AddField(chapter.FieldEndTime, field.TypeFloat64, value)
	}
	if cuo.mutation.VideoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.VideoTable,
			Columns: []string{chapter.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: video.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.VideoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chapter.VideoTable,
			Columns: []string{chapter.VideoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: video.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chapter{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chapter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
