// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/zibbp/eos/ent/playback"
	"github.com/zibbp/eos/ent/predicate"
)

// PlaybackUpdate is the builder for updating Playback entities.
type PlaybackUpdate struct {
	config
	hooks    []Hook
	mutation *PlaybackMutation
}

// Where appends a list predicates to the PlaybackUpdate builder.
func (pu *PlaybackUpdate) Where(ps ...predicate.Playback) *PlaybackUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetVideoID sets the "video_id" field.
func (pu *PlaybackUpdate) SetVideoID(s string) *PlaybackUpdate {
	pu.mutation.SetVideoID(s)
	return pu
}

// SetTimestamp sets the "timestamp" field.
func (pu *PlaybackUpdate) SetTimestamp(i int) *PlaybackUpdate {
	pu.mutation.ResetTimestamp()
	pu.mutation.SetTimestamp(i)
	return pu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (pu *PlaybackUpdate) SetNillableTimestamp(i *int) *PlaybackUpdate {
	if i != nil {
		pu.SetTimestamp(*i)
	}
	return pu
}

// AddTimestamp adds i to the "timestamp" field.
func (pu *PlaybackUpdate) AddTimestamp(i int) *PlaybackUpdate {
	pu.mutation.AddTimestamp(i)
	return pu
}

// SetStatus sets the "status" field.
func (pu *PlaybackUpdate) SetStatus(pl playback.Status) *PlaybackUpdate {
	pu.mutation.SetStatus(pl)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PlaybackUpdate) SetNillableStatus(pl *playback.Status) *PlaybackUpdate {
	if pl != nil {
		pu.SetStatus(*pl)
	}
	return pu
}

// ClearStatus clears the value of the "status" field.
func (pu *PlaybackUpdate) ClearStatus() *PlaybackUpdate {
	pu.mutation.ClearStatus()
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PlaybackUpdate) SetUpdatedAt(t time.Time) *PlaybackUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// Mutation returns the PlaybackMutation object of the builder.
func (pu *PlaybackUpdate) Mutation() *PlaybackMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PlaybackUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks[int, PlaybackMutation](ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PlaybackUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PlaybackUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PlaybackUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PlaybackUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := playback.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PlaybackUpdate) check() error {
	if v, ok := pu.mutation.VideoID(); ok {
		if err := playback.VideoIDValidator(v); err != nil {
			return &ValidationError{Name: "video_id", err: fmt.Errorf(`ent: validator failed for field "Playback.video_id": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := playback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Playback.status": %w`, err)}
		}
	}
	return nil
}

func (pu *PlaybackUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   playback.Table,
			Columns: playback.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: playback.FieldID,
			},
		},
	}
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.VideoID(); ok {
		_spec.SetField(playback.FieldVideoID, field.TypeString, value)
	}
	if value, ok := pu.mutation.Timestamp(); ok {
		_spec.SetField(playback.FieldTimestamp, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedTimestamp(); ok {
		_spec.AddField(playback.FieldTimestamp, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(playback.FieldStatus, field.TypeEnum, value)
	}
	if pu.mutation.StatusCleared() {
		_spec.ClearField(playback.FieldStatus, field.TypeEnum)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(playback.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PlaybackUpdateOne is the builder for updating a single Playback entity.
type PlaybackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlaybackMutation
}

// SetVideoID sets the "video_id" field.
func (puo *PlaybackUpdateOne) SetVideoID(s string) *PlaybackUpdateOne {
	puo.mutation.SetVideoID(s)
	return puo
}

// SetTimestamp sets the "timestamp" field.
func (puo *PlaybackUpdateOne) SetTimestamp(i int) *PlaybackUpdateOne {
	puo.mutation.ResetTimestamp()
	puo.mutation.SetTimestamp(i)
	return puo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (puo *PlaybackUpdateOne) SetNillableTimestamp(i *int) *PlaybackUpdateOne {
	if i != nil {
		puo.SetTimestamp(*i)
	}
	return puo
}

// AddTimestamp adds i to the "timestamp" field.
func (puo *PlaybackUpdateOne) AddTimestamp(i int) *PlaybackUpdateOne {
	puo.mutation.AddTimestamp(i)
	return puo
}

// SetStatus sets the "status" field.
func (puo *PlaybackUpdateOne) SetStatus(pl playback.Status) *PlaybackUpdateOne {
	puo.mutation.SetStatus(pl)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PlaybackUpdateOne) SetNillableStatus(pl *playback.Status) *PlaybackUpdateOne {
	if pl != nil {
		puo.SetStatus(*pl)
	}
	return puo
}

// ClearStatus clears the value of the "status" field.
func (puo *PlaybackUpdateOne) ClearStatus() *PlaybackUpdateOne {
	puo.mutation.ClearStatus()
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PlaybackUpdateOne) SetUpdatedAt(t time.Time) *PlaybackUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// Mutation returns the PlaybackMutation object of the builder.
func (puo *PlaybackUpdateOne) Mutation() *PlaybackMutation {
	return puo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PlaybackUpdateOne) Select(field string, fields ...string) *PlaybackUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Playback entity.
func (puo *PlaybackUpdateOne) Save(ctx context.Context) (*Playback, error) {
	puo.defaults()
	return withHooks[*Playback, PlaybackMutation](ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PlaybackUpdateOne) SaveX(ctx context.Context) *Playback {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PlaybackUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PlaybackUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PlaybackUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := playback.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PlaybackUpdateOne) check() error {
	if v, ok := puo.mutation.VideoID(); ok {
		if err := playback.VideoIDValidator(v); err != nil {
			return &ValidationError{Name: "video_id", err: fmt.Errorf(`ent: validator failed for field "Playback.video_id": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := playback.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Playback.status": %w`, err)}
		}
	}
	return nil
}

func (puo *PlaybackUpdateOne) sqlSave(ctx context.Context) (_node *Playback, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   playback.Table,
			Columns: playback.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: playback.FieldID,
			},
		},
	}
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Playback.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playback.FieldID)
		for _, f := range fields {
			if !playback.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playback.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.VideoID(); ok {
		_spec.SetField(playback.FieldVideoID, field.TypeString, value)
	}
	if value, ok := puo.mutation.Timestamp(); ok {
		_spec.SetField(playback.FieldTimestamp, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedTimestamp(); ok {
		_spec.AddField(playback.FieldTimestamp, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(playback.FieldStatus, field.TypeEnum, value)
	}
	if puo.mutation.StatusCleared() {
		_spec.ClearField(playback.FieldStatus, field.TypeEnum)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(playback.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Playback{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playback.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
